remote_theme: jekyll-theme-minimal
# Site wide configuration

title: EloGroup
logo: /images/elogroup_logo.png
tagline: Uma consultoria que não parece consultoria.
date_format: "%-d %B %Y"
social_links:
  github:  elogroup-consultoria
theme: jekyll-theme-minimal