remote_theme: jekyll-theme-minimal
description: A soul that wonders.
# Site wide configuration

title: EloGroup
tagline: docendo discimus
date_format: "%b %-d, %Y"
social_links:
  github:  elogroup-consultoria
  linkedIn: in/galileu-kim # format: locale/username
theme: jekyll-theme-minimal