remote_theme: jekyll-theme-minimal
description: A soul that wonders.
# Site wide configuration

title: EloGroup
logo: /images/elogroup_logo.jpg
tagline: docendo discimus
date_format: "%b %-d, %Y"
social_links:
  github:  elogroup-consultoria
theme: jekyll-theme-minimal